name: readest

services:
  client:
    container_name: readest-client
    image: ${READEST_IMAGE:-ghcr.io/readest/readest:latest}
    pull_policy: missing
    restart: unless-stopped
    ports:
      - "3000:3000"
